repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports]
-   repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m coverage run -m unittest discover
        language: system
        pass_filenames: false
      - id: coverage
        name: coverage
        entry: python -m coverage report -m --fail-under=100
        language: system
        pass_filenames: false